### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [mcdz/LocalIP#3]
Hi @mcdz ,

Since this app is Apache V2 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind, and it could be useful for some of us.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by mcdz** [comment]
Sure. I'll add it to f-droid. And it's open-source, so, code contribution is welcome 😊

**Comment by IzzySoft** [comment]
F-Droid maintainer here. Would it be possible to have [Fastlane structures](https://gitlab.com/snippets/1895688) in the app's repo, as well as [tagged releases](https://github.com/mcdz/LocalIP/releases)?

PS: For reference, the packaging request for your app was [filed here](https://gitlab.com/fdroid/rfp/-/issues/1500).

**Comment by IzzySoft** [comment]
@mcdz I see this project is dormant meanwhile (no commits for about 5 years) – most likely because the app is "mature" and does not need any changes. Would you still be open for a PR shipping the metadata in fastlane format? We use that at the [IzzyOnDroid repo](https://apt.izzysoft.de/fdroid) as well, and having them here would help us, too.

**Comment by mcdz** [comment]
Thanks, and sorry, just busy with life. So.
Can't do.
I'll discuss / develop it further when I get time.

**Comment by mcdz** [comment]
I'll look into putting it on f-droid.
Apologies for the delays, lots going on.

**Comment by IzzySoft** [comment]
Wow, that was fast – thanks for your swift reply! 🤗 The fastlane tree would in no way conflict with your code, it's a separate directory just containing the app description and some graphics. Would take me less than 5 minutes to create the PR – and you probably less than 2 minutes to review and confirm it causes no issues.

And your app is already [live at IzzyOnDroid](https://apt.izzysoft.de/packages/com.mcdz.seeip) since 2020-09-20 😉 

(for some background: IzzyOnDroid is an F-Droid compatible repository, but independent from F-Droid. We run things on our own resources, so the two complement each other independently)

> I'll look into putting it on f-droid.

Crossed, so **Edit:** having these structures here already, helps you getting started with F-Droid later as well, if you want to publish your app there, too. It's no conflict having it in both places 😉
